-- รันคำสั่ง SQL นี้ใน SQL Editor บน Supabase Dashboard เพื่อสร้างตารางสำหรับแจ้งเตือน Web Push Notification

-- 1. ตารางเก็บข้อมูล Tokens/Subscription ของผู้ใช้/ลูกค้า
CREATE TABLE IF NOT EXISTS public."UserSubscriptions" (
  id bigint generated by default as identity not null,
  "LineID" text not null,       -- ค่า 'customer' สำหรับหน้าบ้านทั่วไป หรือค่า LineID ของสมาชิก
  endpoint text not null,       -- Endpoint URL
  p256dh text not null,         -- p256dh key
  auth text not null,           -- auth key
  platform text null,           -- 'ios' หรือ 'android'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint UserSubscriptions_pkey primary key (id),
  constraint UserSubscriptions_endpoint_key unique (endpoint)
);

CREATE INDEX IF NOT EXISTS "UserSubscriptions_LineID_idx" on public."UserSubscriptions" ("LineID");

-- เปิดให้ตารางสามารถเข้าถึงได้จากภายนอกแบบ Anonymous
ALTER TABLE public."UserSubscriptions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert/upsert" ON public."UserSubscriptions" FOR ALL USING (true) WITH CHECK (true);

-- 2. ตารางเก็บข้อมูลการแจ้งเตือนที่ตั้งเวลาไว้ล่วงหน้า
CREATE TABLE IF NOT EXISTS public."ScheduledNotifications" (
  id bigint generated by default as identity not null,
  title text not null,
  body text not null,
  url text not null default 'index.html',
  scheduled_at timestamp with time zone not null,
  status text not null default 'PENDING', -- 'PENDING', 'SENT', 'FAILED'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint ScheduledNotifications_pkey primary key (id)
);

-- เปิดให้ตารางสามารถเข้าถึงได้จากภายนอกแบบ Anonymous
ALTER TABLE public."ScheduledNotifications" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access for scheduled notifications" ON public."ScheduledNotifications" FOR ALL USING (true) WITH CHECK (true);
